### ISSUE TITLE
Prepare for Android 11

### ISSUE THREAD

**Issue by michaelcarrano** [michaelcarrano/detective-droid#45]
Finally, after many many years of Android existing, this app will need to require a permission to continue to work.

More details - https://developer.android.com/preview/privacy/package-visibility

**Comment by michaelcarrano** [comment]
@alinnert there wouldn't be a permission request as it is not considered a [dangerous permission](https://developer.android.com/guide/topics/permissions/overview#dangerous_permissions).

How/where did you install the app from? Source code or an APK found online somewhere, including Play Store? There was a release where my automation [incorrectly updated the list of libraries](https://github.com/michaelcarrano/detective-droid/pull/50) and uploaded to the Play Store.

I will have to research to see if it is possible to setup an emulator that has Oxygen OS and figure out what might be happening.

**Comment by alinnert** [comment]
@michaelcarrano I've installed it from the Play Store. It's version 2.1.6.
